import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import GridSelect from '../components/gridselect'
import {gridSelData, img} from '../interface'
import lain from "../img/lain.png"
import prinny from "../img/bigPrinny.png"
import porcoEngine from "../img/porcoEngine.png"
import tsubasa from "../img/tsubasa.jpg"
import Dropdown from "../components/dropdown";

const Courses: NextPage = () => {


    return (
        <>

            <div className='absolute overflow-hidden h-[100vh] w-[100vw]'>
                <div
                    className='h-[300vh] bgwave opacity-100 w-[200%] absolute inline top-0  overflow-hidden opacity-60'/>

            </div>
            <div className="">
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <main className="h-[100vh] z-[2] relative m-auto">
                    <div className='w-[90vw] m-auto top-24 relative'>
                        <div className='flex justify-between'>
                            <h1 className='text-white relative text-8xl font-bold mr-0 bg-black bg-opacity-40 text-red-500 border border-4 p pr-4 pl-4 border-red-500'>Benedict</h1>


                        </div>
                        <div className = {"mt-12"}>
                            <Dropdown/>

                        </div>

                    </div>
                </main>



            </div>

        </>
    )
}

export default Courses
