import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import GridSelect from '../components/gridselect'
import { gridSelData,img } from '../interface'
import styles from '../styles/Home.module.css'
import  lain  from "../img/lain.png"

const Home: NextPage = () => {
	const gridData:gridSelData[] = [{name:"name1",img:lain,href:"/about"}]
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-[100vh] z-[2] relative m-auto">
			<div className='w-[90vw] m-auto'>
				<h1 className='text-white top-24 block relative text-8xl font-bold w-0 mr-0 bg-black bg-opacity-40 text-red-500 border border-4 p pr-4 pl-4 border-red-500 inline'>Benedict</h1>
        <div className='top-48 relative'>
          <GridSelect data={JSON.stringify(gridData)} />
        </div>

      </div>
      <div></div>
      </main>
	  <div className='h-[300vh] bgwave opacity-100 w-[200%] absolute block top-0 z-[1] overflow-none opacity-60'/>
	
      <footer className={styles.footer + " bg-white z-[3] w-[100%] relative"}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
