import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import GridSelect from '../components/gridselect'
import { gridSelData,img } from '../interface'
import styles from '../styles/Home.module.css'
import  lain  from "../img/lain.png"

const Home: NextPage = () => {
  function goback() {
    console.log(history.back())
}

	const gridData:gridSelData[] = [{name:"About",img:lain,href:"/about"}]
  return (
    <div className="overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-[100vh] z-[2] relative m-auto">
			<div className='w-[90vw] m-auto'>
        <div className='flex justify-between'>
                <h1 className='text-white top-24 relative text-8xl font-bold mr-0 bg-black bg-opacity-40 text-red-500 border border-4 p pr-4 pl-4 border-red-500 '>Benedict</h1>
				<div className='flex'>
		    		<a href='/about'><button className='text-white m-4 top-24 block relative text-2xl font-bold mr-0 bg-black bg-opacity-40 text-red-500 border border-4 p-2 pr-4 pl-4 border-red-500 hover:bg-black hover:border-white hover:text-white hover:p-2 hover:border-2 hover:font-light transition-all '>About</button></a>
			    	<a href='/services'><button className='text-white m-4 top-24 block relative text-2xl font-bold mr-0 bg-black bg-opacity-40 text-red-500 border border-4 p-2 pr-4 pl-4 border-red-500 hover:bg-black hover:border-white hover:text-white hover:p-2 hover:border-2 hover:font-light transition-all '>Services</button></a>
			    	<a href='/Contacts'><button className='text-white m-4 top-24 block relative text-2xl font-bold mr-0 bg-black bg-opacity-40 text-red-500 border border-4 p-2 pr-4 pl-4 border-red-500 hover:bg-black hover:border-white hover:text-white hover:p-2 hover:border-2 hover:font-light transition-all '>Contacts</button></a>
			    	<a onClick={goback}><button className='text-white m-4 top-24 block relative text-2xl font-bold mr-0 bg-black bg-opacity-40 text-red-500 border border-4 p-2 pr-4 pl-4 border-red-500 hover:bg-black hover:border-white hover:text-white hover:p-2 hover:border-2 hover:font-light transition-all '>Back</button></a>
                </div>
                
                </div>
        <div className='top-48 relative'>
          <GridSelect data={JSON.stringify(gridData)} />
        </div>

      </div>
      <div></div>
      </main>
	  <div className='h-[300vh] bgwave opacity-100 w-[200%] absolute block top-0 z-[1] overflow-none opacity-60'/>
	
      
    </div>
  )
}

export default Home
